# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  rinhabackendapi:
    image: rinhabackendapi
    build:
      context: .
      dockerfile: src/RinhaBackend.Api/Dockerfile
    ports:
      - 9999:9999
